<?php 
$primary_color = get_field('primary_color', 'option');
$secondary_color = get_field('secondary_color', 'option');
$background_color = get_field('background_color', 'option');
$text_color = get_field('text_color', 'option');
$header_background_color = get_field('header_background_color', 'option');
$header_text_color = get_field('header_text_color', 'option');
$footer_background_color = get_field('footer_background_color', 'option');
$footer_text_color = get_field('footer_text_color', 'option');
$announcement_bar_background_color = get_field('announcement_bar_background_color', 'option');
$announcement_bar_text_color = get_field('announcement_bar_text_color', 'option');
function process_font_and_append_css($css, $font_field_name, $css_var_name) {
  $font = get_field($font_field_name, 'option');
  if ($font['files'] || $font['url']) {
      if ($font['upload_type'] == 'local-file') {
          $font_face_src = array_map(function($file) {
              return 'url("' . $file['file']['url'] . '") format("' . $file['file']['subtype'] . '")';
          }, $font['files']);
          $font_face_src = implode(', ', $font_face_src);
          $font_family_name = $font['files'][0]['file']['title'];
?>
@font-face {
  font-family: "<?php echo $font_family_name; ?>";    
  src: <?php echo $font_face_src; ?>;
  font-weight: <?php echo $font['font_weight']; ?>;
  font-style: <?php echo $font['font_style']; ?>;
}
<?php 
          $font_family = '"' . $font_family_name . '", ' . $font['category'];
      } else { 
          $font_family = '"' . $font['font_family'] . '", ' . $font['category'];
      }
      $css .= "$css_var_name: $font_family;";
  }
  return $css;
}?>

:root {<?php 
    $css = '';
    $css = process_font_and_append_css($css, 'primary_font', '--font-primary');
    $css = process_font_and_append_css($css, 'secondary_font', '--font-secondary');
    $css .= $primary_color ? '--color-primary: ' . $primary_color . ';' : '';
    $css .= $secondary_color ? '--color-secondary: ' . $secondary_color . ';' : '';
    $css .= $background_color ? '--color-background: ' . $background_color . ';' : '';
    $css .= $text_color ? '--color-text: ' . $text_color . ';' : '';
    $css .= '--color-white: #ffffff;';
    $css .= '--color-black: #000000;';
    $css .= $footer_background_color ? '--color-footer-background: ' . $footer_background_color . ';' : '';
    $css .= $footer_text_color ? '--color-footer-text: ' . $footer_text_color . ';' : '';
    $css .= $announcement_bar_background_color ? '--color-announcement-bar-background: ' . $announcement_bar_background_color . ';' : '';
    $css .= $announcement_bar_text_color ? '--color-announcement-bar-text: ' . $announcement_bar_text_color . ';' : '';
    $css .= '--font-size-0: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-1: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-2: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-3: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-4: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-5: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-6: clamp(50px, 7.5vw, 144px);';
    $css .= '--font-size-md: 16px;';
    $css .= '--font-size-sm: 14px;';
    $css .= '--container-width: 1200px;';
    $css .= '--content-width: 700px;';
    $css .= '--spacer: clamp(6rem, 10vw, 192px);';
    $css .= '--spacer-sm: calc(var(--spacer) / 2);';
    $css .= '--spacer-lg: calc(var(--spacer) * 2);';
    $css .= '--gutter: clamp(1rem, 3vw, 52px);';
    $css .= '--gutter-sm: calc(var(--gutter) / 2);';
    $css .= '--gutter-lg: calc(var(--gutter) * 2);';
    $css .= '--border-radius: 0.5rem;';
    $css .= '--box-shadow: 0 0 1rem rgba(0, 0, 0, 0.1);';
    $css .= '--transition-ease-in-out: cubic-bezier(0.7, 0, 0.3, 1);';
    echo trim($css);
    ?>}

$breakpoint-mobile: 768px;
$breakpoint-tablet: 1024px;
$breakpoint-content: 1200px;
$breakpoint-laptop: 1440px;
$breakpoint-desktop: 1920px;

@keyframes rotate {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(-360deg);
  }
}
.rotate {
  animation: rotate 5s linear infinite;
}

// File generated by /inc/theme-styles.php
